//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassroomProject_V1._3_.Models
{
    using System;
    using System.Collections.Generic;

    public class AnnouncementDTO
    {
        public Announcement AnnouncementData { get; set; }
        public List<Announcement> AnnouncementList { get; set; }
    }

    public partial class Announcement
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Title { get; set; }
        public string EntireContent { get; set; }
    }
}
